### PR TITLE
Correcting spoiler errors and updating format

### PR DESCRIPTION
**Pull request by mlogie**

### CODE REVIEW

**Comment by mlogie** [comment]
Thanks @fafranco82 .  It looks like my error has caused cards to drop from FA.  Is it possible to get these back in?  The cards are 39, 40, 46, 52, 57, 80, which are the place numbers of the Redemption cards I added.
Should I remove these, commit, then add them in, commit?  Or can you do something on your end?  Thank you

**Comment by fafranco82** [comment]
Apart from the error on set code, you  use the same codes for cards from FA and Redemption... so when importing data, info from Redeptiom replaces FA cards.

I've changed code for Redemption to 15000+pos and now all the cards can be seen, but maybe there are some "glitches", because the import process doesn't clean some fields... Check them visually if there are any errors, I must fix them manually directly on DB.

**Comment by mlogie** [comment]
What a stupid mistake.  Thanks, as always

**Comment by fafranco82** [comment]
Don't worry. I knew instantly what was happened.... because I made that mistake a few times earlier XD

**Comment by mlogie** [comment]
Hi @fafranco82 one lingering issue with this is now Jaro Tapal's Lightsaber in the Faltering Allegiances set has health 11.  I can't remove this data myself.  Would you be able to drop this from the website version?  Cheers.

**Comment by fafranco82** [comment]
Done. Also I've run a "reset" of subtypes, die sides and all susceptible fields that one card could have that another don't (for cards in FA set) and then run an import. I think that with that there couldn't be more errors.

**Pull request merged**
