### PR TITLE
Transoformations set fully spoiled

### PR DESCRIPTION
**Pull request by mlogie**
22 double sided cards just spoiled by ffg.  Hopefully I've edited the schema as necessary.  Deck building may not be perfect with these changes, as they shake things up a bit, but hopefully I haven't broken the website and cards should be viewable.

### CODE REVIEW

**Comment by mlogie** [comment]
I've now also added the additions to the holocron for points balances, format adjustments and restricted list changes

**Comment by fafranco82** [comment]
Thank you SO MUCH!! It's a first step, and I really appreciate it. Now I have to implemtent "Team up" keywords, and maybe filter out sides B plots and characters without points value from deckbuilding...

**Comment by mlogie** [comment]
Awesome.  Hopefully I didn't break anything.  I tried to fix the schema regexes so it'd still work, and added it in to where I think it all needed to go. I was aware that there would likely be fiddly things needing doing to make it all work, but figured if people could actually start building, even if they were allowed to do illegal things for now, that would be fine.  Yes, I forgot about team up, but hopefully you're most of the way there with that thanks to code for Kanan/Cody/Grievous and plots like Spectre.
Glad to see you back on here - I was worried you'd pulled back entirely.  Hope you didn't mind me reaching out to you via FB and your friend Juan Monzon - was worried you might have stopped monitoring the dB.

**Comment by fafranco82** [comment]
I have less time, but I'm still here ;)

**Comment by mlogie** [comment]
That is wonderful news

**Pull request merged**
