### PR TITLE
Ading Faltering Allegiances Sets and spoilers

### PR DESCRIPTION
**Pull request by mlogie**
This pull request is now adding in TTS ID numbers for the Transformations set and adding the first Faltering Allegiances spoilers and the new Renewed Hope Standard (which is basically Trilogies Format + Transformations + Faltering Allegiances)

### CODE REVIEW

**Comment by mlogie** [comment]
@fafranco82 I'm adding the first few spoilers for A Renewed Hope's first expansion: Faltering Allegiances.  There's strong support in the community to add this set, and the new standard: ARN Standard.  Hopefully I've added all the necessary stuff to get this to work.  Once this is approved and once it looks like it's working - I'll submit the other spoilers (there's 10 so far - but I didn't want to enter them all until I was sure you were going to approve more changes and more sets).
For background - these are the community produced sets which continue where FFG left off.  There are plans to have a DB made by the same committee but it's still in development, and a lot of people are keen to start deck building with your db.
If you want, I can send you images for these cards, or you can see them for yourself here: https://echobase.me/player-resources/faltering-allegiances/

**Comment by mlogie** [comment]
@fafranco82 I've now added TTS IDs for Transformations so that this will no longer throw and error when a deck with Transformations cards are loaded in TTS

**Comment by fafranco82** [comment]
At first glance it seems fine! 

About images, I can invita you to the image repo if you want.

**Comment by fafranco82** [comment]
I've only must added the `FA` cycle in `cycles.json`...

I'm not aware of community new content... every new community set will be its own cycle? Or will be there cycles (used by standard and trilogy format) and more than one set for a cycle?

**Comment by mlogie** [comment]
Fantastic, thank you for merging this in.  There will be a lot of very pleased people (myself included).
Yes, please invite me to the image repo and I can get the images on.
Is there a way to get the logos for the sets up too?  I can send you logo images or if you give me access to the relevant repo I can add them.
Thanks again :-)

**Comment by mlogie** [comment]
@fafranco82 to answer the question about community content: there is the Continuing Committee for the game which is creating content with the support of the community.  When they release their full set (later this month) this triggers rotation and creates a new standard format.  I've added this as Renewed Hope Standard to differentiate it from the FFG official standard format.  There will of course by Renewed Hope Infinite and Renewed Hope Trilogy format, but I didn't want to clog the db with niche formats.

**Comment by mlogie** [comment]
Please expect more card commits over the coming days/weeks :-)

**Comment by fafranco82** [comment]
> Yes, please invite me to the image repo and I can get the images on.

Perfect! I need an email address to invite you, or, if you have already have an account on bitbucket, your username there.

> Is there a way to get the logos for the sets up too? I can send you logo images or if you give me access to the relevant repo I can add them.

The logo are in the code repo, https://github.com/fafranco82/swdestinydb, built with IcoMoon (there is a `selectiom.json` file that you can use to import a project on IcoMoon app). The whole process is a little bit tedious... I will tell it to you if you want, but the easiest way is send me the logo, in SVG format if possible, and if not, a PNG.

**Comment by mlogie** [comment]
Just created a bitbucket account: mark.w.logie@gmail.com

**Comment by mlogie** [comment]
Username mlogie

**Comment by mlogie** [comment]
Also @fafranco82 there's been some issues with uploading Transformations cards to the DB.
I don't know how to make this change myself, but in discussion with the mod folks:
Every card from the Transformations set needs to be flagged in two ways:
"BackIsHidden": true needs to change to "BackIsHidden": false;
"UniqueBack": false needs to change to "UniqueBack": true
Are you able to change these somehow for Transformations set card exports?  Maybe a new category in the json for those cards which the export looks at?

**Comment by mlogie** [comment]
In response to my comment above about the tts export, I've attempted to edit the tts export json script.  However, the language is new to me, so I may well have made errors.
The only cards that need these flags swapped are cards where the set code is equal to TR (the transformations set).  This only applies to battlefields, characters and plots (as these are the only cards that can be double sided).  So I've attempted to add some if statements.  I'm assured by the mod folks that if these flags are flipped (in my above comment) the tts thing can work.
Here's a link to my updated json export file (I didn't do this as a pull request as I'm worried about breaking stuff):
https://github.com/mlogie/swdb-java/blob/master/src/AppBundle/Resources/views/Export/tts.json.twig

**Comment by fafranco82** [comment]
The `if` blocks are right... only the variable name. In each `for` loop, the `slot` has been named different, so for example, instead of `{% if slot.card.set.code == "TR" %}`, it should be `{% if battlefield.card.set.code == "TR" %}`, because the variable was named `battefield` in the for loop: `{% for battlefield in deck.slots_by_type.battlefield %}`

Maybe it just was copy&paste code from other point where the variable was named simply `slot` ;)

**Comment by mlogie** [comment]
It was just a copy paste job.  I didn't realise the slot term was specific to that bit of the code.  Are you happy to correct this and merge in, assuming you think this is going to export the files as expected i.e. "BackIsHidden": false and "UniqueBack": true for Transformations cards?

**Comment by fafranco82** [comment]
Ok, I'm gonna try

**Comment by mlogie** [comment]
You're a legend :)

**Comment by fafranco82** [comment]
Done! Give it a try and tell me

**Comment by mlogie** [comment]
Works perfectly.  Just checked for a character a battlefield and a plot and those flags are flipped just as AoZ (mod dev guy) requested.  Now it's down to him to get the mod to work with those flipped flags (he says he's confident he can).  Thank you

**Comment by fafranco82** [comment]
You're welcome!

**Comment by mlogie** [comment]
I'm working on those set logos, and if you can add me to the bitbucket, that'd be great :)

**Comment by mlogie** [comment]
The logo for Faltering Allegiances is here: https://github.com/mlogie/swdb-java/blob/master/Production_symbol.svg

**Comment by mlogie** [comment]
Also can be found here if github download is tricky: https://filebin.net/9ecgumdx7mt31s18

**Comment by fafranco82** [comment]
> I'm working on those set logos, and if you can add me to the bitbucket, that'd be great :)

I invited you by email... don't you get an invitation??

**Comment by fafranco82** [comment]
Icon added ;)

**Comment by mlogie** [comment]
Sorry, didn't check my email.  Never used bitbucket before, so I've done a test upload of a card that was missing from the Convergence set: 09053 Assassin Droid.  I've pushed it to the repo (https://bitbucket.org/fafranco82/swdestinydb-img/src/master/en/09/).  Is there a further step I need to take?
Thanks for adding the icon.  Looking forward to seeing it in action on the site.  Will try to fill in the gaps at some point.

**Comment by fafranco82** [comment]
Yes, I must deployed then in the server (a git pull and execute and script to create symbolic links for missing localised images)

**Comment by fafranco82** [comment]
Image added ;)

**Comment by mlogie** [comment]
Nice one.  I thought I'd rescaled it properly but I had not so I've just overwritten that image.  Hopefully I'll get them all right next time.

**Comment by mlogie** [comment]
Hi @fafranco82 
I've now uploaded the images for all the missing ones in Convergence.
Also, I have icons for the sets with missing icons (Transformations, Covert Missions and Faltering Allegiances).  You should be able to download them from here:
https://drive.google.com/drive/folders/1Wmvqxf5JFuSxz05T0ZPoan3LQOCAI3Kl?usp=sharing
Please let me know if you have any trouble.  Cheers,
Mark

**Comment by fafranco82** [comment]
Thanks for the icons! They are up on the server :) As so the images

**Pull request merged**
