### PR TITLE
Adding spoilers from FFG

### PR DESCRIPTION
**Pull request by mlogie**
All the new spoilers from the FFG video, plus a couple of minor edits, such as Execute Order 66 has a deck limit of 6 (4 from plot, 2 for deck) and minor typos.
Also, tagging Aftermath as a reprint, even though it is functionally different from the original.  This is in line with previous commits (such as Crime Lord being functionally different but still a repeat) and makes sense as it's exactly the same card title, meaning you cannot have two copies of it and the old aftermath in your deck (in infinite).

### CODE REVIEW

**Comment by fafranco82** [comment]
Thanks for the spoilers! About Aftermath, I agree with you.

But about Exceute Order 66 I have my doubts how to resolve this... Are the extra Execute Order 66 part of the deck? You can shuffle up to 4 set-aside copies of it, but you may want to shuffle 3 in a game, and 4 in another (whatever reason you have to do something like that...). So I was thinking in simply leaving as it, like a normal card... Anyway, increasing its deck limit to 6 have another side problem: The deck size. It must still be 30 and if you include 6 copies of Execute Order, you will exceed this limit. I should code the deck validator to adjust deck size... 

Anyway, there is time until SoH release, so I will merge this now and change it again if needed.

**Comment by mlogie** [comment]
Yes, I agree, the Execute Order 66s are a potential problem as you can shuffle anywhere between 0 and 4 per game as you wish e.g. 0 copies against an Ewok swarm, 4 copies against Padme Boushh.  I guess if Order 66 is the plot, the deck needs to be 34, with exactly 4 Execute Order 66 (like Lightsaber Mastery is a  32 card deck with 2 moves), then players can then choose when playing the deck to manually remove some copies if they want.  Though it's a little messy.
Maybe it could be possible to create a sidebar, following the format of the battlefield, where you can add your 4 execute order 66s or your two lightsaber mastery moves.  Though then you would, I guess, need to have Execute Order 66 entered twice into the database - once as an event and once a sidebar card.

**Comment by fafranco82** [comment]
Or maybe do it more simple, maybe only assuming that if you include Order 66 plot, you will bring with you up to 4 extra copies of Execute Order 66, and doing nothing special about this :S

**Comment by mlogie** [comment]
That could work.  It's not like lightsaber mastery where you get to choose the moves.
Only issue is downloading to TTS format (which is what I use a lot of my decks for), though if you could get the TTS object to include the four copies of Execute Order 66 when the plot is included in the deck, that would solve this problem.

**Comment by fafranco82** [comment]
Or TTS loading for you 4 copies of Execute Order 66 so you can include whatever you want. I will talk with TTS mod's author :)

**Pull request merged**
