### PR TITLE
Adding in 4040 plot

### PR DESCRIPTION
**Pull request by mlogie**

### CODE REVIEW

**Comment by mlogie** [comment]
Thanks @fafranco82.
After discussion with the ARH guys, they're on board with the idea of having this as a character. That way we don't have to solve the multiple plots thing. That's why I changed this to a character in my third commit (I was going to update the image shortly). I think it's probably cleaner as a character, and means new characters can be added to this set to create new formats.

**Comment by mlogie** [comment]
However, if you think the multiple plots thing can be solved relatively easily, then great, keep this as a plot. Please let me know whether you think this can be done as a plot, as they're hoping to release this card as a promo for their upcoming infinite event this weekend. Thanks again @fafranco82

**Comment by fafranco82** [comment]
Ah, ok, I think was an error, because it has no health that is compulsory on characters. I'll change it back to character and give it health 0 (take it into account to recreate image).

**Comment by mlogie** [comment]
Ah right, gotcha. Thanks

**Comment by mlogie** [comment]
While you're here: is there any reason I can't change the 'position' number of cards to reflect their actual position in the set. I've just been using sequential numbers, but card 3 has 2 sides, card 4 has 2 sides, so the position number of card 5 is 7 and so on. Is there a problem if multiple cards share a position number, or if I update the schema so that 'position' can include a letter?

**Comment by mlogie** [comment]
Hi @fafranco82 I just tried to build a deck using that character.  The db doesn't seem to like it.  When you try to select it, where it normally gives you the option of 1 for 1 copy of a diceless character, it says -1. When you click that, it doesn't appear on the deck builder. Maybe this will work better as a plot after all?

**Comment by mlogie** [comment]
I also tried saving and it says method not allowed. Perhaps a plot is a better solution if there's something about a character that prevents negative points?

**Comment by fafranco82** [comment]
I think I finally did it :) Finally, it's better as a plot. Makes more sense than a character and give fewer problems. And it was easy to allow 2 plots. When you select a plot, first every plot is unselected (this way you're forced to have only one plot, and battlefield). I only added that don't unselect 15101 plot and that's all :)

**Comment by mlogie** [comment]
Excellent. Just built a 4040 deck and it accepted it, points and cards! It doesn't complain about number of cards, and the points adds up perfectly.
However, it isn't letting me select 2 plots.

**Comment by mlogie** [comment]
It was a cache issue. BOOM. Good work.
Quick question - I mentioned it above - is it possible for more than one card to have the same 'position' flag? So that A and B sides can have the same numerical code? I've had quite a few people say they'd like that, but didn't want to risk breaking something where these have to be unique or something.
Thanks again

**Comment by fafranco82** [comment]
There is no unique restriction on DB, and that field is only use to show what card number is (i.e `Awakenings #23`), so there should not be any problem. But it must be a number, the same number for both.

**Comment by mlogie** [comment]
Great - I'll be submitting a pull request shortly then :)

**Pull request merged**
