### PR TITLE
Adding no answer errata

### PR DESCRIPTION
**Pull request by mlogie**

### CODE REVIEW

**Comment by fafranco82** [comment]
What is the source of this erratum? I don't find it...

**Comment by mlogie** [comment]
Page 27 of the new rules reference

**Comment by mlogie** [comment]
Sorry, page 28

**Comment by mlogie** [comment]
Picture1

**Comment by fafranco82** [comment]
It's a little bit strange... that's the "Clarifications" sections, but it seems like an errata... If I treat it like that, I guess I must do the same with Unutei Force Tree, don't you think?

**Comment by mlogie** [comment]
Absolutely.  Even though it's in clarifications, it's definitely an errata to the way the card plays.  Uneti Force Tree has already been updated to reflect this change (I think by me a month or so ago) - this was errata'd on the day of release.

**Comment by fafranco82** [comment]
Ok then :)

**Comment by mlogie** [comment]
Ah, I see, yes, I didn't add the has errata flag.  I can add that now

**Pull request merged**
