### PR TITLE
All Redemption

### PR DESCRIPTION
**Pull request by mlogie**
Thanks @fafranco82 and hopefully I haven't made any errors this time

### CODE REVIEW

**Comment by fafranco82** [comment]
You can always follow the instructions to perform validation check :P.

In short, if you have python installed, make sure `jsonschema` is installed with `pip install -U jsonschema`

And then you only need to type `python validate.py -f`

**Comment by fafranco82** [comment]
image

See? It's useful XD

**Comment by mlogie** [comment]
Ah yes, I will get python installed and do this next time, thank you

**Comment by mlogie** [comment]
And thanks for approving so quickly :)

**Pull request merged**
